// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function Exit():Promise<void>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function Scan(arg1:settings.ScanParams):Promise<void>;
