name: Build Wails Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            pkg-config

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Use the Go version compatible with Wails

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the Node.js version required by your frontend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend # Modify this if your frontend is in a different directory

      - name: Build Wails project for Linux
        run: wails build

      - name: Build Wails project for Windows
        run: wails build --platform windows

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dark-scanner-linux
          path: ./build/bin/dark-scanner  # Adjust the path if needed

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dark-scanner-windows.exe
          path: ./build/bin/dark-scanner.exe
          